name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare release
        run: ./.github/workflows/scripts/get-next-version.sh
      - name: Generate notes
        run: ./.github/workflows/scripts/generate-release-notes.sh
      - name: Package artifacts
        run: ./.github/workflows/scripts/create-release-packages.sh
      - name: Publish release
        run: ./.github/workflows/scripts/create-github-release.sh
